services:
  db:
    image: mysql:latest
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - appNetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    container_name: app-laravel
    ports:
      - "8080:80"
    volumes:
      - .:/app
    networks:
      - appNetwork
    restart: always
    command: bash -c "composer install && php artisan migrate && php artisan key:generate && apache2-foreground"
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

networks:
  appNetwork:
    name: appNetwork
    driver: bridge
